Run integration tests on primary workflow #309

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -12,8 +12,8 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [windows-latest, ubuntu-latest]
-        java: [1.8, 11, 13]
+        os: [ windows-latest, ubuntu-latest ]
+        java: [ 1.8, 11, 13 ]
     steps:
       - uses: actions/checkout@v2
       - name: Set up JDK
@@ -27,4 +27,23 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-jdk-${{ matrix.java }}-mvn-
       - name: Build it with Maven
-        run: mvn clean test -B -Pqulice # Only run unit tests
+        run: |
+          if [ "$RUNNER_OS" == "Linux" ]; then
+             mvn clean verify -B -Pqulice
+          elif [ "$RUNNER_OS" == "Windows" ]; then
+             mvn clean test -B -Pqulice
+          else
+             echo "$RUNNER_OS not supported"
+             exit 1
+          fi
+        shell: bash
+  # @todo #309:30min Fix ci integration tests with testcontainers for Windows.
+  #  The Windows command run only unit tests (Integration tests are ignored).
+  #  When we execute {@code mvn clean verify -B -Pqulice}, integration tests based on testcontainers
+  #  failed to run with this message : `main org.testcontainers.dockerclient.DockerClientProviderStrategy:
+  #  NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (windows containers
+  #  are currently not supported)`.
+  #  We have to find the right configuration that allow us to run docker in docker
+  #  for Windows and replace Windows command. You can find at
+  #  {@link https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/}
+  #  some documentation about that.
